name: deploy to preview

on:
  push:
    branches:
      - master

env:
  STORAGE_NAME_PREFIX: osprs${{ github.event.pull_request.number }}

jobs:
  preview:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Packages
        run: npm install

      - name: Build packages
        run: | 
          cat package.json | jq '.scripts | keys[] | select( test("^build\\-")) | .[6:]' > build-selection.txt
          cat package.json | jq '.scripts | keys[] | select( test("^build\\-")) | .[6:] | sub("-"; "")' | xargs -I@ echo "$STORAGE_NAME_PREFIX@" > storage-selection.txt
          mkdir out
          cat build-selection.txt | xargs -L1 -I@ echo 'npm run build-@; cp -r www out/$STORAGE_NAME_PREFIX$(echo @ | sed "s/-//g")'
        env:
          STORAGE_NAME_PREFIX: ${{ env.STORAGE_NAME_PREFIX}}
          SENTRY_DSN: https://a0d00f7ce1924a0a8521a8fe88af734c@o197997.ingest.sentry.io/5801653

      - name: Generate Deploy Script
        run: | 
          cat storage-selection.txt | xargs -I@ echo "
              az storage account create --kind StorageV2 --name @ --resource-group $RESSOURCE_GROUP --subscription $AZURE_SUBSCRIPTION_ID
              az storage blob service-properties update --account-name @ --static-website --404-document 404.html --index-document index.html --subscription $AZURE_SUBSCRIPTION_ID
              az storage blob upload-batch -d '\$web' -s ./out/@ --account-name @ --account-key \"\$(az storage account keys list --account-name @ --resource-group  $RESSOURCE_GROUP --subscription $AZURE_SUBSCRIPTION_ID --query \"[0].value\")\" --overwrite --subscription $AZURE_SUBSCRIPTION_ID" > deploy.sh
        env:
          RESSOURCE_GROUP: ${{ SECRETS.RESSOURCE_GROUP }}
          AZURE_SUBSCRIPTION_ID: ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
          STORAGE_NAME_PREFIX: ${{ env.STORAGE_NAME_PREFIX}}

      # Setup Preview
      - name: Azure Login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.41.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/deploy.sh
            $GITHUB_WORKSPACE/deploy.sh

      # - name: Find Comment
      #   uses: peter-evans/find-comment@v1
      #   id: fc
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body-includes: This PR is available as a preview

      # - id: get-comment-body
      #   run: |
      #     cat storage-selection.txt | xargs -L1 -I@ echo " - [@](https://@.z16.web.core.windows.net)" >> $GITHUB_OUTPUT

      # - name: Create comment
      #   if: ${{ steps.fc.outputs.comment-id == 0 }}
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       This PR is available as a preview: 
      #       ${{ steps.get-comment-body.outputs.body }}
      #     reaction-type: "rocket"